# Generated by Django 2.0.6 on 2018-07-06 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180626_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_image/noprofile.png', upload_to='profile_image'),
        ),
    ]
