# Generated by Django 2.0.6 on 2018-06-26 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='users',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
