# Generated by Django 2.0.6 on 2018-07-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendshiprequest',
            unique_together=set(),
        ),
    ]
